---
- name: Set initial password
    block:
      - name: Set Prism Central "admin" user password
        uri:
          url: "https://{{ nutanix_prism_pwd_host }}:{{ nutanix_port }}/PrismGateway/services/rest/v1/utils/change_default_system_password"
          method: POST
          validate_certs: "{{ validate_certs }}"
          body_format: json
          body:
            oldPassword: "{{ nutanix_prism_initial_password }}"
            newPassword: "{{ nutanix_prism_new_password }}"
          force_basic_auth: yes
          username: "{{ nutanix_prism_pwd_username }}"
          password: "{{ nutanix_prism_initial_password }}"
          status_code: 200
          return_content: yes
        register: nutanix_prism_pwd_change
        ignore_errors: no

    - debug:
        var: nutanix_prism_pwd_change
      when: nutanix_debug

    - assert:
        that: 
          - nutanix_prism_pwd_change.json.value
        success_msg: "Initial account password change for '{{ nutanix_prism_pwd_username }}' succeeded"
        fail_msg: "'{{ nutanix_prism_pwd_username }}' initial account password change failed."
